# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Dylan Curley

application: mlab-metrics-definition
version: 1
runtime: python27
threadsafe: false
api_version: 1

libraries:
- name: django
  version: "1.3"

handlers:
- url: /static
  static_dir: static

- url: /oauth2callback
  script: oauth2client/appengine.py

- url: /(|intro|contact)
  script: main.py

- url: /.*
  script: main.py
  login: admin
